import { closeSync, createWriteStream, existsSync, mkdirSync, openSync, readdirSync } from 'node:fs';
import { chmod, readFile, rename, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { Readable } from 'node:stream';
import { pipeline } from 'node:stream/promises';
import { spawn, spawnSync } from 'node:child_process';
import { normalizeMusicConfig } from './music.js';

export const DEFAULT_MUSIC_RUNTIME_DIR = 'data/music-runtime';
export const DEFAULT_LAVALINK_JAR_URL = 'https://github.com/lavalink-devs/Lavalink/releases/latest/download/Lavalink.jar';
export const YOUTUBE_SOURCE_RELEASE_API = 'https://api.github.com/repos/lavalink-devs/youtube-source/releases/latest';
export const LAVALINK_VERSION_ENDPOINT = '/version';
export const GENERATED_CONFIG_MARKER = '# Generated by HeeHeeBot music auto setup';
export const FALLBACK_YOUTUBE_PLUGIN_VERSION = '1.18.1';
export const DEFAULT_LAVALINK_BUFFER_DURATION_MS = 1_000;
export const DEFAULT_LAVALINK_FRAME_BUFFER_DURATION_MS = 10_000;
export const DEFAULT_LAVALINK_OPUS_ENCODING_QUALITY = 10;
export const DEFAULT_LAVALINK_RESAMPLING_QUALITY = 'MEDIUM';
const DEFAULT_READY_TIMEOUT_MS = 180_000;
const DEFAULT_READY_POLL_MS = 1_500;
const WINDOWS_EXECUTABLE_SUFFIX = '.exe';

export async function ensureMusicRuntime(rawConfig = {}, {
  fetchFn = globalThis.fetch,
  spawnFn = spawn,
  spawnSyncFn = spawnSync,
  logger = console,
  platform = process.platform,
  arch = process.arch
} = {}) {
  const config = normalizeMusicAutoSetupConfig(rawConfig);
  const cleanupCallbacks = [];

  if (!config.autoSetup) {
    return {
      musicConfig: normalizeMusicConfig(config),
      cleanup() {}
    };
  }

  const runtimeDir = resolve(config.runtimeDir);
  mkdirSync(runtimeDir, { recursive: true });

  const localLavalink = !config.lavalink.host;
  if (localLavalink) {
    config.lavalink.javaCommand = resolveJava17Command({
      javaCommand: config.lavalink.javaCommand,
      spawnSyncFn,
      platform,
      logger
    });
    const jarPath = await ensureLavalinkJar({ config, runtimeDir, fetchFn, logger });
    const youtubePluginVersion = await resolveYoutubePluginVersion({ config, fetchFn, logger });
    await ensureLavalinkApplicationConfig({ config, runtimeDir, youtubePluginVersion, logger });

    config.lavalink.host = '127.0.0.1';
    config.lavalink.secure = false;

    if (config.lavalink.autoStart && !(await isLavalinkReachable(config, fetchFn))) {
      const child = startLocalLavalink({
        jarPath,
        runtimeDir,
        javaCommand: config.lavalink.javaCommand,
        spawnFn,
        logger
      });
      cleanupCallbacks.push(() => stopLocalProcess(child, logger));
      await waitForLavalinkReady(config, {
        fetchFn,
        logger,
        child,
        logPath: child.lavalinkLogPath
      });
    }
  }

  if (config.ytdlp.enabled && config.ytdlp.autoDownload) {
    config.ytdlp.path = await ensureYtDlpBinary({ config, runtimeDir, fetchFn, platform, arch, logger });
  }

  return {
    musicConfig: normalizeMusicConfig(config),
    cleanup() {
      for (const callback of cleanupCallbacks.reverse()) callback();
    }
  };
}

export function normalizeMusicAutoSetupConfig(config = {}) {
  const normalized = normalizeMusicConfig(config);
  const autoSetup = parseBoolean(config.autoSetup, true);
  const runtimeDir = normalizeOptionalString(config.runtimeDir) ?? DEFAULT_MUSIC_RUNTIME_DIR;

  return {
    ...normalized,
    autoSetup,
    runtimeDir,
    lavalink: {
      ...normalized.lavalink,
      autoStart: parseBoolean(config.lavalink?.autoStart ?? config.autoStartLavalink, true),
      jarPath: normalizeOptionalString(config.lavalink?.jarPath),
      jarUrl: normalizeOptionalString(config.lavalink?.jarUrl) ?? DEFAULT_LAVALINK_JAR_URL,
      javaCommand: normalizeOptionalString(config.lavalink?.javaCommand),
      configPath: normalizeOptionalString(config.lavalink?.configPath),
      overwriteGeneratedConfig: parseBoolean(config.lavalink?.overwriteGeneratedConfig, true),
      youtubePluginVersion: normalizeOptionalString(config.lavalink?.youtubePluginVersion),
      readyTimeoutMs: clampInteger(config.lavalink?.readyTimeoutMs ?? DEFAULT_READY_TIMEOUT_MS, 5_000, 300_000),
      bufferDurationMs: clampInteger(
        config.lavalink?.bufferDurationMs ?? DEFAULT_LAVALINK_BUFFER_DURATION_MS,
        40,
        10_000
      ),
      frameBufferDurationMs: clampInteger(
        config.lavalink?.frameBufferDurationMs ?? DEFAULT_LAVALINK_FRAME_BUFFER_DURATION_MS,
        1_000,
        60_000
      ),
      opusEncodingQuality: clampInteger(
        config.lavalink?.opusEncodingQuality ?? DEFAULT_LAVALINK_OPUS_ENCODING_QUALITY,
        0,
        10
      ),
      resamplingQuality: normalizeResamplingQuality(config.lavalink?.resamplingQuality),
      nonAllocatingFrameBuffer: parseBoolean(config.lavalink?.nonAllocatingFrameBuffer, true),
      useSeekGhosting: parseBoolean(config.lavalink?.useSeekGhosting, true)
    },
    ytdlp: {
      ...normalized.ytdlp,
      enabled: parseBoolean(config.ytdlp?.enabled, autoSetup),
      autoDownload: parseBoolean(config.ytdlp?.autoDownload, true),
      assetUrl: normalizeOptionalString(config.ytdlp?.assetUrl)
    }
  };
}

async function ensureLavalinkJar({ config, runtimeDir, fetchFn, logger }) {
  const jarPath = resolve(config.lavalink.jarPath ?? join(runtimeDir, 'Lavalink.jar'));
  if (existsSync(jarPath)) return jarPath;

  logger.log?.(`Lavalink.jar가 없어 다운로드합니다: ${config.lavalink.jarUrl}`);
  await downloadFile(config.lavalink.jarUrl, jarPath, { fetchFn });
  return jarPath;
}

async function resolveYoutubePluginVersion({ config, fetchFn, logger }) {
  if (config.lavalink.youtubePluginVersion) return config.lavalink.youtubePluginVersion;

  try {
    const response = await fetchFn(YOUTUBE_SOURCE_RELEASE_API, {
      headers: { 'User-Agent': 'heeheebot-music-setup' }
    });
    if (!response.ok) throw new Error(`GitHub release API ${response.status}`);
    const payload = await response.json();
    const tag = normalizeOptionalString(payload?.tag_name);
    if (tag) return tag.replace(/^v/i, '');
  } catch (error) {
    logger.warn?.(`YouTube source 최신 버전을 확인하지 못해 fallback ${FALLBACK_YOUTUBE_PLUGIN_VERSION}을 사용합니다:`, error);
  }

  return FALLBACK_YOUTUBE_PLUGIN_VERSION;
}

async function ensureLavalinkApplicationConfig({ config, runtimeDir, youtubePluginVersion, logger }) {
  const configPath = resolve(config.lavalink.configPath ?? join(runtimeDir, 'application.yml'));
  if (existsSync(configPath)) {
    const existing = await readFile(configPath, 'utf8');
    if (!existing.includes(GENERATED_CONFIG_MARKER) || !config.lavalink.overwriteGeneratedConfig) {
      logger.log?.(`기존 Lavalink application.yml을 유지합니다: ${configPath}`);
      return configPath;
    }
  }

  const yaml = createLavalinkApplicationYaml({
    port: config.lavalink.port,
    password: config.lavalink.password,
    youtubePluginVersion,
    bufferDurationMs: config.lavalink.bufferDurationMs,
    frameBufferDurationMs: config.lavalink.frameBufferDurationMs,
    opusEncodingQuality: config.lavalink.opusEncodingQuality,
    resamplingQuality: config.lavalink.resamplingQuality,
    nonAllocatingFrameBuffer: config.lavalink.nonAllocatingFrameBuffer,
    useSeekGhosting: config.lavalink.useSeekGhosting
  });
  mkdirSync(dirname(configPath), { recursive: true });
  await writeFile(configPath, yaml, 'utf8');
  logger.log?.(`Lavalink application.yml을 준비했습니다: ${configPath}`);
  return configPath;
}

function createLavalinkApplicationYaml({
  port,
  password,
  youtubePluginVersion,
  bufferDurationMs,
  frameBufferDurationMs,
  opusEncodingQuality,
  resamplingQuality,
  nonAllocatingFrameBuffer,
  useSeekGhosting
}) {
  return `${GENERATED_CONFIG_MARKER}
server:
  port: ${port}
  address: 127.0.0.1
  http2:
    enabled: false

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:${escapeYamlString(youtubePluginVersion)}"
      snapshot: false
  server:
    password: "${escapeYamlString(password)}"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      nico: true
      http: true
      local: false
    filters:
      volume: false
      equalizer: false
      karaoke: false
      timescale: false
      tremolo: false
      vibrato: false
      distortion: false
      rotation: false
      channelMix: false
      lowPass: false
    nonAllocatingFrameBuffer: ${nonAllocatingFrameBuffer}
    bufferDurationMs: ${bufferDurationMs}
    frameBufferDurationMs: ${frameBufferDurationMs}
    opusEncodingQuality: ${opusEncodingQuality}
    resamplingQuality: ${resamplingQuality}
    trackStuckThresholdMs: 10000
    useSeekGhosting: ${useSeekGhosting}
    playerUpdateInterval: 5
    youtubePlaylistLoadLimit: 6
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - ANDROID_VR
      - WEB
      - WEBEMBEDDED

logging:
  level:
    root: INFO
    lavalink: INFO
`;
}

function startLocalLavalink({ jarPath, runtimeDir, javaCommand = 'java', spawnFn, logger }) {
  const logPath = join(runtimeDir, 'lavalink.log');
  const logFd = openSync(logPath, 'a');
  const child = spawnFn(javaCommand, ['-jar', jarPath], {
    cwd: runtimeDir,
    stdio: ['ignore', logFd, logFd],
    windowsHide: true
  });
  closeSync(logFd);
  child.lavalinkLogPath = logPath;
  child.on?.('error', (error) => logger.error?.('로컬 Lavalink 시작 실패:', error));
  child.on?.('exit', (code, signal) => {
    if (code !== 0 && signal !== 'SIGTERM') {
      logger.warn?.(`로컬 Lavalink가 종료되었습니다. code=${code} signal=${signal}. 로그: ${logPath}`);
    }
  });
  logger.log?.(`로컬 Lavalink를 시작했습니다. 로그: ${logPath}`);
  return child;
}

async function waitForLavalinkReady(config, { fetchFn, logger, child = null, logPath = null }) {
  const deadline = Date.now() + config.lavalink.readyTimeoutMs;
  let lastError = null;

  while (Date.now() < deadline) {
    if (hasChildExited(child)) {
      throw new Error(await createLavalinkStartupErrorMessage({
        reason: `로컬 Lavalink 프로세스가 준비되기 전에 종료되었습니다. exitCode=${child.exitCode ?? 'unknown'} signal=${child.signalCode ?? 'none'}`,
        config,
        logPath
      }));
    }

    try {
      if (await isLavalinkReachable(config, fetchFn)) {
        logger.log?.('로컬 Lavalink 준비 완료.');
        return true;
      }
    } catch (error) {
      lastError = error;
    }
    await delay(DEFAULT_READY_POLL_MS);
  }

  throw new Error(await createLavalinkStartupErrorMessage({
    reason: `Lavalink가 ${config.lavalink.readyTimeoutMs}ms 안에 준비되지 않았습니다.${lastError ? ` 마지막 오류: ${lastError.message}` : ''}`,
    config,
    logPath
  }));
}

function hasChildExited(child) {
  return Boolean(child) && (child.exitCode !== null && child.exitCode !== undefined);
}

async function createLavalinkStartupErrorMessage({ reason, config, logPath }) {
  const logTail = await readLogTail(logPath);
  return [
    reason,
    `확인 대상: http://${config.lavalink.host}:${config.lavalink.port}${LAVALINK_VERSION_ENDPOINT}`,
    logPath ? `로그 파일: ${logPath}` : null,
    logTail ? `\n--- lavalink.log 마지막 내용 ---\n${logTail}` : 'lavalink.log를 읽지 못했습니다.'
  ].filter(Boolean).join('\n');
}

async function readLogTail(logPath, maxLines = 120) {
  if (!logPath) return '';
  try {
    const content = await readFile(logPath, 'utf8');
    return content.split(/\r?\n/).slice(-maxLines).join('\n').trim();
  } catch {
    return '';
  }
}

async function isLavalinkReachable(config, fetchFn) {
  try {
    const protocol = config.lavalink.secure ? 'https' : 'http';
    const response = await fetchFn(`${protocol}://${config.lavalink.host}:${config.lavalink.port}${LAVALINK_VERSION_ENDPOINT}`, {
      headers: {
        Authorization: config.lavalink.password
      },
      signal: AbortSignal.timeout(2_000)
    });
    return response.ok;
  } catch {
    return false;
  }
}

async function ensureYtDlpBinary({ config, runtimeDir, fetchFn, platform, arch, logger }) {
  const customPath = normalizeOptionalString(config.ytdlp.path);
  if (customPath && customPath !== 'yt-dlp' && existsSync(customPath)) return customPath;

  if (customPath === 'yt-dlp' && isCommandAvailable('yt-dlp')) return customPath;

  const asset = getYtDlpAsset({ platform, arch });
  const targetPath = resolve(join(runtimeDir, asset.fileName));
  if (existsSync(targetPath)) return targetPath;

  const url = config.ytdlp.assetUrl ?? asset.url;
  logger.log?.(`yt-dlp 바이너리가 없어 다운로드합니다: ${url}`);
  await downloadFile(url, targetPath, { fetchFn });
  if (platform !== 'win32') await chmod(targetPath, 0o755);
  return targetPath;
}

function getYtDlpAsset({ platform, arch }) {
  const base = 'https://github.com/yt-dlp/yt-dlp/releases/latest/download';
  if (platform === 'win32') {
    return { fileName: `yt-dlp${WINDOWS_EXECUTABLE_SUFFIX}`, url: `${base}/yt-dlp.exe` };
  }
  if (platform === 'darwin') {
    return { fileName: 'yt-dlp_macos', url: `${base}/yt-dlp_macos` };
  }
  if (platform === 'linux' && arch === 'arm64') {
    return { fileName: 'yt-dlp_linux_aarch64', url: `${base}/yt-dlp_linux_aarch64` };
  }
  if (platform === 'linux') {
    return { fileName: 'yt-dlp_linux', url: `${base}/yt-dlp_linux` };
  }
  return { fileName: 'yt-dlp', url: `${base}/yt-dlp` };
}

async function downloadFile(url, destination, { fetchFn }) {
  const response = await fetchFn(url, {
    headers: { 'User-Agent': 'heeheebot-music-setup' }
  });
  if (!response.ok) throw new Error(`다운로드 실패 (${response.status}): ${url}`);

  mkdirSync(dirname(destination), { recursive: true });
  const tempPath = `${destination}.tmp-${process.pid}-${Date.now()}`;
  await pipeline(Readable.fromWeb(response.body), createWriteStream(tempPath));
  await rename(tempPath, destination);
}

export function resolveJava17Command({
  javaCommand = null,
  spawnSyncFn = spawnSync,
  platform = process.platform,
  env = process.env,
  logger = console
} = {}) {
  const candidates = collectJavaCommandCandidates({ javaCommand, platform, env });
  let newestTooOldMajor = null;

  for (const candidate of candidates) {
    const result = spawnSyncFn(candidate, ['-version'], { encoding: 'utf8' });
    if (result.error || result.status !== 0) continue;

    const output = `${result.stderr ?? ''}\n${result.stdout ?? ''}`;
    const major = parseJavaMajorVersion(output);
    if (major === null || major >= 17) {
      if (candidate !== 'java') {
        logger.log?.(`Java 17+ 실행 파일을 찾았습니다: ${candidate}`);
      }
      return candidate;
    }

    newestTooOldMajor = Math.max(newestTooOldMajor ?? 0, major);
  }

  if (newestTooOldMajor !== null) {
    throw new Error(`Lavalink 자동 실행에는 Java 17 이상이 필요합니다. 현재 찾은 Java는 최대 ${newestTooOldMajor}입니다.`);
  }

  throw new Error([
    'Lavalink 자동 실행에는 Java 17 이상이 필요합니다.',
    'Java를 방금 설치했다면 터미널을 완전히 닫고 새로 열어 `java -version`이 17 이상으로 나오는지 확인한 뒤 다시 `npm start`를 실행해주세요.',
    '그래도 안 되면 `.env`에 `LAVALINK_JAVA_COMMAND=C:\\\\Program Files\\\\Eclipse Adoptium\\\\jdk-17...\\\\bin\\\\java.exe`처럼 java.exe 전체 경로를 지정해주세요.'
  ].join(' '));
}

function collectJavaCommandCandidates({ javaCommand, platform, env }) {
  const candidates = [];
  const addCandidate = (candidate) => {
    const normalized = normalizeOptionalString(candidate);
    if (normalized && !candidates.includes(normalized)) candidates.push(normalized);
  };

  addCandidate(javaCommand);
  addCandidate('java');
  for (const variableName of ['JAVA_HOME', 'JDK_HOME', 'JRE_HOME']) {
    addCandidate(buildJavaExecutablePath(env?.[variableName], platform));
  }

  if (platform === 'win32') {
    for (const root of getWindowsJavaSearchRoots(env)) {
      for (const directory of listSortedDirectories(root)) {
        addCandidate(join(root, directory, 'bin', 'java.exe'));
      }
    }
  }

  return candidates;
}

function buildJavaExecutablePath(root, platform) {
  const normalizedRoot = normalizeOptionalString(root);
  if (!normalizedRoot) return null;
  return join(normalizedRoot, 'bin', platform === 'win32' ? 'java.exe' : 'java');
}

function getWindowsJavaSearchRoots(env) {
  return [
    env?.ProgramFiles ? join(env.ProgramFiles, 'Eclipse Adoptium') : null,
    env?.['ProgramFiles(x86)'] ? join(env['ProgramFiles(x86)'], 'Eclipse Adoptium') : null,
    env?.ProgramFiles ? join(env.ProgramFiles, 'Java') : null,
    env?.['ProgramFiles(x86)'] ? join(env['ProgramFiles(x86)'], 'Java') : null
  ].filter(Boolean);
}

function listSortedDirectories(root) {
  try {
    return readdirSync(root, { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => entry.name)
      .sort((left, right) => right.localeCompare(left, undefined, { numeric: true, sensitivity: 'base' }));
  } catch {
    return [];
  }
}

function parseJavaMajorVersion(output) {
  const match = String(output).match(/version "(\d+)(?:\.(\d+))?/i);
  if (!match) return null;
  const first = Number(match[1]);
  const second = Number(match[2]);
  if (first === 1 && Number.isFinite(second)) return second;
  return Number.isFinite(first) ? first : null;
}

function stopLocalProcess(child, logger) {
  if (!child || child.killed) return;
  logger.log?.('로컬 Lavalink를 종료합니다.');
  child.kill('SIGTERM');
}

function isCommandAvailable(command) {
  const result = spawnSync(process.platform === 'win32' ? 'where' : 'which', [command], {
    stdio: 'ignore'
  });
  return result.status === 0;
}

function normalizeOptionalString(value) {
  if (value === undefined || value === null) return null;
  const normalized = String(value).trim();
  return normalized ? normalized : null;
}

function parseBoolean(value, defaultValue) {
  if (value === undefined || value === null || value === '') return defaultValue;
  return !['0', 'false', 'no', 'off'].includes(String(value).trim().toLowerCase());
}

function normalizeResamplingQuality(value) {
  const normalized = String(value ?? DEFAULT_LAVALINK_RESAMPLING_QUALITY).trim().toUpperCase();
  return ['LOW', 'MEDIUM', 'HIGH'].includes(normalized) ? normalized : DEFAULT_LAVALINK_RESAMPLING_QUALITY;
}

function clampInteger(value, min, max) {
  const number = Number(value);
  if (!Number.isFinite(number)) return min;
  return Math.max(min, Math.min(max, Math.trunc(number)));
}

function escapeYamlString(value) {
  return String(value ?? '').replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

function delay(ms) {
  return new Promise((resolveDelay) => setTimeout(resolveDelay, ms));
}
