import { closeSync, createWriteStream, existsSync, mkdirSync, openSync } from 'node:fs';
import { chmod, readFile, rename, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { Readable } from 'node:stream';
import { pipeline } from 'node:stream/promises';
import { spawn, spawnSync } from 'node:child_process';
import { normalizeMusicConfig } from './music.js';

export const DEFAULT_MUSIC_RUNTIME_DIR = 'data/music-runtime';
export const DEFAULT_LAVALINK_JAR_URL = 'https://github.com/lavalink-devs/Lavalink/releases/latest/download/Lavalink.jar';
export const YOUTUBE_SOURCE_RELEASE_API = 'https://api.github.com/repos/lavalink-devs/youtube-source/releases/latest';
export const LAVALINK_VERSION_ENDPOINT = '/version';
export const GENERATED_CONFIG_MARKER = '# Generated by HeeHeeBot music auto setup';
export const FALLBACK_YOUTUBE_PLUGIN_VERSION = '1.18.1';
const DEFAULT_READY_TIMEOUT_MS = 90_000;
const DEFAULT_READY_POLL_MS = 1_500;
const WINDOWS_EXECUTABLE_SUFFIX = '.exe';

export async function ensureMusicRuntime(rawConfig = {}, {
  fetchFn = globalThis.fetch,
  spawnFn = spawn,
  spawnSyncFn = spawnSync,
  logger = console,
  platform = process.platform,
  arch = process.arch
} = {}) {
  const config = normalizeMusicAutoSetupConfig(rawConfig);
  const cleanupCallbacks = [];

  if (!config.autoSetup) {
    return {
      musicConfig: normalizeMusicConfig(config),
      cleanup() {}
    };
  }

  const runtimeDir = resolve(config.runtimeDir);
  mkdirSync(runtimeDir, { recursive: true });

  const localLavalink = !config.lavalink.host;
  if (localLavalink) {
    assertJava17Available({ spawnSyncFn });
    const jarPath = await ensureLavalinkJar({ config, runtimeDir, fetchFn, logger });
    const youtubePluginVersion = await resolveYoutubePluginVersion({ config, fetchFn, logger });
    await ensureLavalinkApplicationConfig({ config, runtimeDir, youtubePluginVersion, logger });

    config.lavalink.host = '127.0.0.1';
    config.lavalink.secure = false;

    if (config.lavalink.autoStart && !(await isLavalinkReachable(config, fetchFn))) {
      const child = startLocalLavalink({ jarPath, runtimeDir, spawnFn, logger });
      cleanupCallbacks.push(() => stopLocalProcess(child, logger));
      await waitForLavalinkReady(config, { fetchFn, logger });
    }
  }

  if (config.ytdlp.enabled && config.ytdlp.autoDownload) {
    config.ytdlp.path = await ensureYtDlpBinary({ config, runtimeDir, fetchFn, platform, arch, logger });
  }

  return {
    musicConfig: normalizeMusicConfig(config),
    cleanup() {
      for (const callback of cleanupCallbacks.reverse()) callback();
    }
  };
}

export function normalizeMusicAutoSetupConfig(config = {}) {
  const normalized = normalizeMusicConfig(config);
  const autoSetup = parseBoolean(config.autoSetup, true);
  const runtimeDir = normalizeOptionalString(config.runtimeDir) ?? DEFAULT_MUSIC_RUNTIME_DIR;

  return {
    ...normalized,
    autoSetup,
    runtimeDir,
    lavalink: {
      ...normalized.lavalink,
      autoStart: parseBoolean(config.lavalink?.autoStart ?? config.autoStartLavalink, true),
      jarPath: normalizeOptionalString(config.lavalink?.jarPath),
      jarUrl: normalizeOptionalString(config.lavalink?.jarUrl) ?? DEFAULT_LAVALINK_JAR_URL,
      configPath: normalizeOptionalString(config.lavalink?.configPath),
      overwriteGeneratedConfig: parseBoolean(config.lavalink?.overwriteGeneratedConfig, true),
      youtubePluginVersion: normalizeOptionalString(config.lavalink?.youtubePluginVersion),
      readyTimeoutMs: clampInteger(config.lavalink?.readyTimeoutMs ?? DEFAULT_READY_TIMEOUT_MS, 5_000, 300_000)
    },
    ytdlp: {
      ...normalized.ytdlp,
      enabled: parseBoolean(config.ytdlp?.enabled, autoSetup),
      autoDownload: parseBoolean(config.ytdlp?.autoDownload, true),
      assetUrl: normalizeOptionalString(config.ytdlp?.assetUrl)
    }
  };
}

async function ensureLavalinkJar({ config, runtimeDir, fetchFn, logger }) {
  const jarPath = resolve(config.lavalink.jarPath ?? join(runtimeDir, 'Lavalink.jar'));
  if (existsSync(jarPath)) return jarPath;

  logger.log?.(`Lavalink.jar가 없어 다운로드합니다: ${config.lavalink.jarUrl}`);
  await downloadFile(config.lavalink.jarUrl, jarPath, { fetchFn });
  return jarPath;
}

async function resolveYoutubePluginVersion({ config, fetchFn, logger }) {
  if (config.lavalink.youtubePluginVersion) return config.lavalink.youtubePluginVersion;

  try {
    const response = await fetchFn(YOUTUBE_SOURCE_RELEASE_API, {
      headers: { 'User-Agent': 'heeheebot-music-setup' }
    });
    if (!response.ok) throw new Error(`GitHub release API ${response.status}`);
    const payload = await response.json();
    const tag = normalizeOptionalString(payload?.tag_name);
    if (tag) return tag.replace(/^v/i, '');
  } catch (error) {
    logger.warn?.(`YouTube source 최신 버전을 확인하지 못해 fallback ${FALLBACK_YOUTUBE_PLUGIN_VERSION}을 사용합니다:`, error);
  }

  return FALLBACK_YOUTUBE_PLUGIN_VERSION;
}

async function ensureLavalinkApplicationConfig({ config, runtimeDir, youtubePluginVersion, logger }) {
  const configPath = resolve(config.lavalink.configPath ?? join(runtimeDir, 'application.yml'));
  if (existsSync(configPath)) {
    const existing = await readFile(configPath, 'utf8');
    if (!existing.includes(GENERATED_CONFIG_MARKER) || !config.lavalink.overwriteGeneratedConfig) {
      logger.log?.(`기존 Lavalink application.yml을 유지합니다: ${configPath}`);
      return configPath;
    }
  }

  const yaml = createLavalinkApplicationYaml({
    port: config.lavalink.port,
    password: config.lavalink.password,
    youtubePluginVersion
  });
  mkdirSync(dirname(configPath), { recursive: true });
  await writeFile(configPath, yaml, 'utf8');
  logger.log?.(`Lavalink application.yml을 준비했습니다: ${configPath}`);
  return configPath;
}

function createLavalinkApplicationYaml({ port, password, youtubePluginVersion }) {
  return `${GENERATED_CONFIG_MARKER}
server:
  port: ${port}
  address: 127.0.0.1
  http2:
    enabled: false

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:${escapeYamlString(youtubePluginVersion)}"
      snapshot: false
  server:
    password: "${escapeYamlString(password)}"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      nico: true
      http: true
      local: false
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    playerUpdateInterval: 5
    youtubePlaylistLoadLimit: 6
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - ANDROID_VR
      - WEB
      - WEBEMBEDDED

logging:
  level:
    root: INFO
    lavalink: INFO
`;
}

function startLocalLavalink({ jarPath, runtimeDir, spawnFn, logger }) {
  const logPath = join(runtimeDir, 'lavalink.log');
  const logFd = openSync(logPath, 'a');
  const child = spawnFn('java', ['-jar', jarPath], {
    cwd: runtimeDir,
    stdio: ['ignore', logFd, logFd],
    windowsHide: true
  });
  closeSync(logFd);
  child.on?.('error', (error) => logger.error?.('로컬 Lavalink 시작 실패:', error));
  child.on?.('exit', (code, signal) => {
    if (code !== 0 && signal !== 'SIGTERM') {
      logger.warn?.(`로컬 Lavalink가 종료되었습니다. code=${code} signal=${signal}. 로그: ${logPath}`);
    }
  });
  logger.log?.(`로컬 Lavalink를 시작했습니다. 로그: ${logPath}`);
  return child;
}

async function waitForLavalinkReady(config, { fetchFn, logger }) {
  const deadline = Date.now() + config.lavalink.readyTimeoutMs;
  let lastError = null;

  while (Date.now() < deadline) {
    try {
      if (await isLavalinkReachable(config, fetchFn)) {
        logger.log?.('로컬 Lavalink 준비 완료.');
        return true;
      }
    } catch (error) {
      lastError = error;
    }
    await delay(DEFAULT_READY_POLL_MS);
  }

  throw new Error(`Lavalink가 ${config.lavalink.readyTimeoutMs}ms 안에 준비되지 않았습니다. data/music-runtime/lavalink.log를 확인해주세요.${lastError ? ` 마지막 오류: ${lastError.message}` : ''}`);
}

async function isLavalinkReachable(config, fetchFn) {
  try {
    const protocol = config.lavalink.secure ? 'https' : 'http';
    const response = await fetchFn(`${protocol}://${config.lavalink.host}:${config.lavalink.port}${LAVALINK_VERSION_ENDPOINT}`, {
      signal: AbortSignal.timeout(2_000)
    });
    return response.ok;
  } catch {
    return false;
  }
}

async function ensureYtDlpBinary({ config, runtimeDir, fetchFn, platform, arch, logger }) {
  const customPath = normalizeOptionalString(config.ytdlp.path);
  if (customPath && customPath !== 'yt-dlp' && existsSync(customPath)) return customPath;

  if (customPath === 'yt-dlp' && isCommandAvailable('yt-dlp')) return customPath;

  const asset = getYtDlpAsset({ platform, arch });
  const targetPath = resolve(join(runtimeDir, asset.fileName));
  if (existsSync(targetPath)) return targetPath;

  const url = config.ytdlp.assetUrl ?? asset.url;
  logger.log?.(`yt-dlp 바이너리가 없어 다운로드합니다: ${url}`);
  await downloadFile(url, targetPath, { fetchFn });
  if (platform !== 'win32') await chmod(targetPath, 0o755);
  return targetPath;
}

function getYtDlpAsset({ platform, arch }) {
  const base = 'https://github.com/yt-dlp/yt-dlp/releases/latest/download';
  if (platform === 'win32') {
    return { fileName: `yt-dlp${WINDOWS_EXECUTABLE_SUFFIX}`, url: `${base}/yt-dlp.exe` };
  }
  if (platform === 'darwin') {
    return { fileName: 'yt-dlp_macos', url: `${base}/yt-dlp_macos` };
  }
  if (platform === 'linux' && arch === 'arm64') {
    return { fileName: 'yt-dlp_linux_aarch64', url: `${base}/yt-dlp_linux_aarch64` };
  }
  if (platform === 'linux') {
    return { fileName: 'yt-dlp_linux', url: `${base}/yt-dlp_linux` };
  }
  return { fileName: 'yt-dlp', url: `${base}/yt-dlp` };
}

async function downloadFile(url, destination, { fetchFn }) {
  const response = await fetchFn(url, {
    headers: { 'User-Agent': 'heeheebot-music-setup' }
  });
  if (!response.ok) throw new Error(`다운로드 실패 (${response.status}): ${url}`);

  mkdirSync(dirname(destination), { recursive: true });
  const tempPath = `${destination}.tmp-${process.pid}-${Date.now()}`;
  await pipeline(Readable.fromWeb(response.body), createWriteStream(tempPath));
  await rename(tempPath, destination);
}

function assertJava17Available({ spawnSyncFn }) {
  const result = spawnSyncFn('java', ['-version'], { encoding: 'utf8' });
  if (result.error || result.status !== 0) {
    throw new Error('Lavalink 자동 실행에는 Java 17 이상이 필요합니다. Java를 설치한 뒤 다시 npm start를 실행해주세요.');
  }

  const output = `${result.stderr ?? ''}\n${result.stdout ?? ''}`;
  const major = parseJavaMajorVersion(output);
  if (major !== null && major < 17) {
    throw new Error(`Lavalink 자동 실행에는 Java 17 이상이 필요합니다. 현재 Java ${major}로 감지되었습니다.`);
  }
}

function parseJavaMajorVersion(output) {
  const match = String(output).match(/version "(\d+)(?:\.(\d+))?/i);
  if (!match) return null;
  const first = Number(match[1]);
  const second = Number(match[2]);
  if (first === 1 && Number.isFinite(second)) return second;
  return Number.isFinite(first) ? first : null;
}

function stopLocalProcess(child, logger) {
  if (!child || child.killed) return;
  logger.log?.('로컬 Lavalink를 종료합니다.');
  child.kill('SIGTERM');
}

function isCommandAvailable(command) {
  const result = spawnSync(process.platform === 'win32' ? 'where' : 'which', [command], {
    stdio: 'ignore'
  });
  return result.status === 0;
}

function normalizeOptionalString(value) {
  if (value === undefined || value === null) return null;
  const normalized = String(value).trim();
  return normalized ? normalized : null;
}

function parseBoolean(value, defaultValue) {
  if (value === undefined || value === null || value === '') return defaultValue;
  return !['0', 'false', 'no', 'off'].includes(String(value).trim().toLowerCase());
}

function clampInteger(value, min, max) {
  const number = Number(value);
  if (!Number.isFinite(number)) return min;
  return Math.max(min, Math.min(max, Math.trunc(number)));
}

function escapeYamlString(value) {
  return String(value ?? '').replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

function delay(ms) {
  return new Promise((resolveDelay) => setTimeout(resolveDelay, ms));
}
