#!/usr/bin/env python3
"""Postprocess the generated sword forge sheets into per-level transparent icons.

The raw art is generated by agent-sprite-forge/generate2dsprite as four 5x5
magenta-background prop sheets. This extractor keeps each connected sword/effect
component with the nearest nominal grid cell, which prevents cross-cell pieces
from being duplicated or clipped when a generated sword slightly exceeds its
cell boundary.
"""
from __future__ import annotations

import json
import math
import shutil
from pathlib import Path

import numpy as np
from PIL import Image

REPO_ROOT = Path(__file__).resolve().parents[1]
ROOT = REPO_ROOT / 'assets' / 'sword' / 'level-atlas'
RAW_ROOT = ROOT / 'raw'
OUT_ROOT = ROOT / 'extracted'
ROWS = COLS = 5
ICON = 256
FIT_SCALE = 0.82
BG_RB_MIN = 220
BG_G_MAX = 100
MIN_COMPONENT_AREA = 3


def background_mask(arr: np.ndarray) -> np.ndarray:
    """Return bright-magenta background pixels from an RGB array."""
    r = arr[..., 0].astype(np.int16)
    g = arr[..., 1].astype(np.int16)
    b = arr[..., 2].astype(np.int16)
    return (r >= BG_RB_MIN) & (b >= BG_RB_MIN) & (g <= BG_G_MAX) & (np.abs(r - b) <= 70)


def connected_components(mask: np.ndarray):
    h, w = mask.shape
    seen = np.zeros((h, w), dtype=bool)
    neighbors = [(-1, -1), (0, -1), (1, -1), (-1, 0), (1, 0), (-1, 1), (0, 1), (1, 1)]
    comps = []

    for y in range(h):
        xs = np.flatnonzero(mask[y] & ~seen[y])
        for x0 in xs:
            if seen[y, x0] or not mask[y, x0]:
                continue
            stack = [(int(x0), int(y))]
            seen[y, x0] = True
            xs_list = []
            ys_list = []
            area = 0
            minx = maxx = int(x0)
            miny = maxy = int(y)
            sumx = sumy = 0

            while stack:
                x, yy = stack.pop()
                xs_list.append(x)
                ys_list.append(yy)
                area += 1
                sumx += x
                sumy += yy
                minx = min(minx, x)
                maxx = max(maxx, x)
                miny = min(miny, yy)
                maxy = max(maxy, yy)

                for dx, dy in neighbors:
                    nx = x + dx
                    ny = yy + dy
                    if 0 <= nx < w and 0 <= ny < h and not seen[ny, nx] and mask[ny, nx]:
                        seen[ny, nx] = True
                        stack.append((nx, ny))

            if area >= MIN_COMPONENT_AREA:
                comps.append({
                    'area': area,
                    'bbox': (minx, miny, maxx + 1, maxy + 1),
                    'centroid': (sumx / area, sumy / area),
                    'xs': np.array(xs_list, dtype=np.int32),
                    'ys': np.array(ys_list, dtype=np.int32),
                })

    return comps


def nearest_cell(cx: float, cy: float, cell_w: float, cell_h: float) -> int:
    col = int(round((cx - cell_w / 2) / cell_w))
    row = int(round((cy - cell_h / 2) / cell_h))
    col = max(0, min(COLS - 1, col))
    row = max(0, min(ROWS - 1, row))
    return row * COLS + col


def is_noise_for_cell(comp, cell_idx: int, cell_w: float, cell_h: float) -> bool:
    if comp['area'] >= 10:
        return False
    row, col = divmod(cell_idx, COLS)
    center = ((col + 0.5) * cell_w, (row + 0.5) * cell_h)
    cx, cy = comp['centroid']
    dist = math.hypot(cx - center[0], cy - center[1])
    return dist > max(cell_w, cell_h) * 0.45


def crop_icon(src_arr: np.ndarray, assigned: np.ndarray, cell_idx: int):
    ys, xs = np.nonzero(assigned == cell_idx)
    if len(xs) == 0:
        return Image.new('RGBA', (ICON, ICON), (0, 0, 0, 0)), None

    x0, x1 = int(xs.min()), int(xs.max()) + 1
    y0, y1 = int(ys.min()), int(ys.max()) + 1
    pad = 2
    h, w = assigned.shape
    x0 = max(0, x0 - pad)
    y0 = max(0, y0 - pad)
    x1 = min(w, x1 + pad)
    y1 = min(h, y1 + pad)

    crop = src_arr[y0:y1, x0:x1].copy()
    mask_crop = assigned[y0:y1, x0:x1] == cell_idx
    rgba = np.dstack([crop[..., :3], mask_crop.astype(np.uint8) * 255])
    im = Image.fromarray(rgba, 'RGBA')

    arr = np.array(im)
    arr[..., 3] = np.where(background_mask(arr[..., :3]), 0, arr[..., 3])
    im = Image.fromarray(arr, 'RGBA')

    bbox = im.getchannel('A').getbbox()
    if not bbox:
        return Image.new('RGBA', (ICON, ICON), (0, 0, 0, 0)), [x0, y0, x1, y1]

    im = im.crop(bbox)
    scale = min((ICON * FIT_SCALE) / im.width, (ICON * FIT_SCALE) / im.height, 1.0)
    new_size = (max(1, int(round(im.width * scale))), max(1, int(round(im.height * scale))))
    im = im.resize(new_size, Image.Resampling.LANCZOS)

    canvas = Image.new('RGBA', (ICON, ICON), (0, 0, 0, 0))
    canvas.alpha_composite(im, ((ICON - im.width) // 2, (ICON - im.height) // 2))
    return canvas, [x0, y0, x1, y1]


def process_batch(batch: int, names: dict[str, str]):
    start_level = (batch - 1) * 25 + 1
    raw = RAW_ROOT / f'batch-{batch:02d}' / 'raw-sheet.png'
    out = OUT_ROOT / f'batch-{batch:02d}'
    out.mkdir(parents=True, exist_ok=True)

    img = Image.open(raw).convert('RGBA')
    arr = np.array(img)
    h, w = arr.shape[:2]
    cell_w = w / COLS
    cell_h = h / ROWS
    fg = ~background_mask(arr[..., :3])
    comps = connected_components(fg)
    assigned = np.full((h, w), -1, dtype=np.int16)
    kept_by_cell = [[] for _ in range(ROWS * COLS)]
    dropped = 0

    for comp in comps:
        cell = nearest_cell(*comp['centroid'], cell_w, cell_h)
        if is_noise_for_cell(comp, cell, cell_w, cell_h):
            dropped += 1
            continue
        assigned[comp['ys'], comp['xs']] = cell
        kept_by_cell[cell].append({
            'area': comp['area'],
            'bbox': list(comp['bbox']),
            'centroid': [round(comp['centroid'][0], 2), round(comp['centroid'][1], 2)],
        })

    sheet = Image.new('RGBA', (COLS * ICON, ROWS * ICON), (0, 0, 0, 0))
    levels_meta = []
    for idx in range(ROWS * COLS):
        level = start_level + idx
        icon, src_bbox = crop_icon(arr, assigned, idx)
        filename = f'sword_{level:03d}.png'
        icon.save(out / filename)
        row, col = divmod(idx, COLS)
        sheet.alpha_composite(icon, (col * ICON, row * ICON))

        alpha_bbox = icon.getchannel('A').getbbox()
        margins = None
        edge_touch = False
        if alpha_bbox:
            ax0, ay0, ax1, ay1 = alpha_bbox
            margins = [ax0, ay0, ICON - ax1, ICON - ay1]
            edge_touch = min(margins) < 2

        levels_meta.append({
            'level': level,
            'name': names[str(level)],
            'file': filename,
            'source_bbox': src_bbox,
            'components_kept': len(kept_by_cell[idx]),
            'foreground_bbox': list(alpha_bbox) if alpha_bbox else None,
            'margins': margins,
            'edge_touch': edge_touch,
        })

    sheet.save(out / 'sheet-transparent.png')
    (out / 'extract-meta.json').write_text(json.dumps({
        'source': str(raw.relative_to(REPO_ROOT)),
        'rows': ROWS,
        'cols': COLS,
        'levels': levels_meta,
        'method': 'global connected-component assignment to nearest 5x5 cell center, magenta chroma key, 256px centered icons',
        'threshold': {'rb_min': BG_RB_MIN, 'g_max': BG_G_MAX},
        'component_count': len(comps),
        'tiny_components_dropped': dropped,
    }, ensure_ascii=False, indent=2), encoding='utf-8')
    return len(comps), dropped


def assemble_all_atlas(names: dict[str, str]):
    atlas = Image.new('RGBA', (10 * ICON, 10 * ICON), (0, 0, 0, 0))
    index = []
    for level in range(1, 101):
        batch = (level - 1) // 25 + 1
        src = OUT_ROOT / f'batch-{batch:02d}' / f'sword_{level:03d}.png'
        icon = Image.open(src).convert('RGBA')
        row, col = divmod(level - 1, 10)
        atlas.alpha_composite(icon, (col * ICON, row * ICON))
        index.append({
            'level': level,
            'name': names[str(level)],
            'image': str(src.relative_to(ROOT)),
            'batch': batch,
        })
    atlas.save(OUT_ROOT / 'atlas-100-transparent.png')
    (OUT_ROOT / 'index.json').write_text(json.dumps(index, ensure_ascii=False, indent=2), encoding='utf-8')


def main():
    names = json.loads((ROOT / 'names.json').read_text(encoding='utf-8'))
    if OUT_ROOT.exists():
        shutil.rmtree(OUT_ROOT)
    OUT_ROOT.mkdir(parents=True)
    for batch in range(1, 5):
        comps, dropped = process_batch(batch, names)
        print(f'batch-{batch:02d}: components={comps}, dropped={dropped}')
    assemble_all_atlas(names)


if __name__ == '__main__':
    main()
